<div id="termsModal" class="modal4" style="display:none;">
    <div class="modal-content4">
        <span class="close" onclick="closeTerms()">&times;</span>
        <h2>Terms And Conditions & Privacy Policy</h2>
        <hr>
        <div class="terms-content">
            <p>&nbsp;&nbsp;&nbsp;Our Privacy Policy was last updated on December 6, 2024</p>
            <p>&nbsp;&nbsp;&nbsp;This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>&nbsp;&nbsp;&nbsp;We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy was generated by TermsFeed Privacy Policy Generator.</p>

            <h3>Use License</h3>
            <p>&nbsp;&nbsp;&nbsp;You are granted a limited license to use the Madridejos Home Residence Management System for personal, non-commercial purposes, subject to these terms and conditions.</p>

            <h3>Limitations</h3>
            <p>You must not:</p>
            <ul>
                <li>Republish material from this system</li>
                <li>Sell, rent, or sub-license material from this system</li>
                <li>Reproduce, duplicate, or copy material from this system</li>
            </ul>

            <h3>Modifications</h3>
            <p>&nbsp;&nbsp;&nbsp;We may revise these terms from time to time. Please check this page regularly to ensure you are happy with any changes.</p>
            <hr>
            <h3>Privacy Policy</h3>
            <p>&nbsp;&nbsp;&nbsp;At Madridejos Home Residence Management System, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and disclose your information when you use our system.</p>

            <h3>Information We Collect</h3>
            <p>We may collect personal information such as:</p>
            <ul>
                <li>Name</li>
                <li>Email address</li>
                <li>Contact information</li>
                <li>Usage data</li>
                <li>Any other information you provide voluntarily</li>
            </ul>

            <h3>How We Use Your Information</h3>
            <p>The information we collect is used to:</p>
            <ul>
                <li>Provide and manage the services of the Madridejos Home Residence Management System</li>
                <li>Improve the system and respond to feedback</li>
                <li>Contact you for system-related notices and updates</li>
                <li>Ensure security and compliance with legal obligations</li>
            </ul>

            <h3>How We Protect Your Information</h3>
            <p>&nbsp;&nbsp;&nbsp;We implement security measures to safeguard your personal information. However, no method of electronic transmission is entirely secure, and we cannot guarantee absolute security.</p>

            <h3>Sharing Your Information</h3>
            <p>&nbsp;&nbsp;&nbsp;We do not sell, rent, or lease your personal information to third parties. We may share your information with third-party service providers who help us manage the system and with law enforcement or government authorities if required by law.</p>

            <h3>Your Rights</h3>
            <p>&nbsp;&nbsp;&nbsp;You have the right to access, update, or delete your personal information. If you wish to exercise any of these rights, please contact us through the system's contact page.</p>

            <h3>Changes to the Privacy Policy</h3>
            <p>&nbsp;&nbsp;&nbsp;We may update our Privacy Policy from time to time. We encourage you to review this policy regularly for any changes.</p>

            <h3>Contact Us</h3>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
                <li>By visiting this page on our website: <a href="https://lawishomeresidences.com">https://lawishomeresidences.com</a></li>
                <li>By sending us an email: lawishomeresidences@gmail.com</li>
            </ul>
        </div>
    </div>
</div>
